use_frameworks!

target 'EHHorizontalFixedWidthItemsView_Example' do
  pod 'EHHorizontalFixedWidthItemsView', :path => '../'

  target 'EHHorizontalFixedWidthItemsView_Tests' do
    inherit! :search_paths

    
  end
end
